tasks:
  # random utilities 
  - name: utils
    before: |
      sudo apt-get install tree
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  # https://docs.aws.amazon.com/powershell/v5/userguide/install-aws.tools-on-linux-macos.html
  # https://docs.aws.amazon.com/powershell/v5/reference/
  - name: powershell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget apt-transport-https software-properties-common
      source /etc/os-release
      wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      rm packages-microsoft-prod.deb
      sudo apt-get update
      sudo apt-get install -y powershell
      pwsh
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module -Name AWS.Tools.Installer -Force
      Install-AWSToolsModule AWS.Tools.S3 -CleanUp -Confirm:$false
      exit
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
