#! /usr/bin/env bash

echo "== create bucket"

if [ -z "$1" ]; then
   BUCKET_NAME="$1"
fi

BUCKET_NAME="$1"

#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration LocationConstraint=eu-west-3 \
--query Location \
--output text

